spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ai_studyhub}?useSSL=${DB_SSL:false}&verifyServerCertificate=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123}

logging:
  level:
    com.studyhub: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

app:
  frontend-url: http://localhost:5173
